import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import Navigation from './_components/navigation/navigation';
import Footer from './_components/footer';
import './globals.css';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en' className={`dark ${roboto.className}`}>
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;